
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-02-24T14:17:37+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "e986cd0d31825e509ac5e1b3a80123f5a302591b",
 "version": "1.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
